name: Check For Prohibited Elements

on:
  pull_request:
    types: [opened, synchronize]
    
permissions:
  pull-requests: write

jobs:
  scan_html_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Scan for HTML tags
        id: scan
        run: |
          TAGS=("script" "iframe" "embed" "object")
          # See https://www.itsdanjc.com/wiki/help/rules-and-restrictions#prohibited
          
          # Get a list of files changed in the pull request
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Initialize an empty variable to track found tags
          FOUND_TAGS=""

          # Loop over each changed file and each tag
          for file in $CHANGED_FILES; do
            # Skip non-Markdown files
            if [[ "$file" != *.md ]]; then
              continue
            fi
            for tag in "${TAGS[@]}"; do
              # Search for the tag in the file and add to FOUND_TAGS if found
              if grep -qi "<$tag" "$file"; then
                FOUND_TAGS+="$tag found in $file\n"
              fi
            done
          done

          # Check if any tags were found
          if [[ -n "$FOUND_TAGS" ]]; then
            echo -e "Prohibited tags found:\n$FOUND_TAGS"
            exit 1
          else
            echo "No prohibited HTML tags found in the changed files."
          fi

      - name: Close pull request if prohibited tags are found
        if: failure()  # This step only runs if the previous step fails
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh pr close "${{ github.event.pull_request.number }}" --comment "Pull request closed due to prohibited content.\nFound: ${FOUND_TAGS}\nSee the [docs](https://www.itsdanjc.com/wiki/help/rules-and-restrictions#prohibited) for more info."
